from .AifeProcess import AifeProcess
from .AwsProcess import AwsProcess
from .BfcProcess import BfcProcess
from .BreProcess import BreProcess
from .DecpAwsProcess import DecpAwsProcess
from .EmarProcess import EmarProcess
from .LyonProcess import LyonProcess
from .MaxiProcess import MaxiProcess
from .MegaProcess import MegaProcess
from .PesProcess import PesProcess
from .SampleXmlProcess import SampleXmlProcess
from .SampleJsonProcess import SampleJsonProcess